name: midterm
description: "WanderWise Project App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/WanderWise.png
    - assets/bali.jpg
    - assets/paris.jpg
    - assets/yenizellanda.jpg
    - assets/sliderimage1.jpg
    - assets/sliderimage2.jpg
    - assets/sliderimage3.jpg
